import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { Provider } from './Provider';
import { SessionContext } from '@/context/sessionProvider';
import PushNotification from '@/context/PushNotification';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});

const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <link rel='manifest' href='/manifest.json' />

      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ToastContainer
          position='top-right'
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme='colored'
        />
        <Provider>
          {/* <PushNotification /> */}
          <SessionContext>
            <main>{children}</main>
          </SessionContext>
        </Provider>
      </body>
    </html>
  );
}
